[package]
name = "client_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
common_lib = { path = "../common_lib" }
serde.workspace = true
url.workspace = true
derive_more.workspace = true
serde-wasm-bindgen = "0.4.5"
web-sys = { version = "0.3.60", features = ["EventTarget", "HtmlElement"] }
js-sys = "0.3.60"
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.33"
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "568b5b13c80b0296213901cf45c7669a6a496582", features = [
    "suspense",
    "hydrate",
] }
sycamore-router = { git = "https://github.com/sycamore-rs/sycamore", rev = "568b5b13c80b0296213901cf45c7669a6a496582" }

[features]
ssg = ["sycamore/ssr"]
