[workspace]
members = ["common_lib", "indexer", "client", "client_ui"]

[workspace.dependencies]
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
toml = "0.5.9"
reqwest = { version = "0.11.13", features = ["json"] }
tokio = { version = "1.22.0", features = ["full"] }
url = { version = "2.3.1", features = ["serde"] }
derive_more = "0.99.17"
elasticsearch = "8.5.0-alpha.1"
sha2 = "0.10.6"
base16ct = { version = "0.1.1", features = ["alloc"] }
chrono = { version = "0.4.23", features = ["serde"] }
once_cell = "1.16.0"
