[package]
name = "common_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_with.workspace = true
url.workspace = true
derive_more.workspace = true
chrono.workspace = true
uuid.workspace = true
